export const Constants: any = {
  pokedex: 'Pokedex',
  search: 'Search for Pokémon by name or using the National Pokédex number.',
  whatPokemon: 'What Pokémon are you looking for?',
  filters: 'Filters',
  advancedSearch:
    'Use advanced search to explore Pokémon by type, weakness, height and more!',
  types: 'Types',
  weaknesses: 'Weaknesses',
  heights: 'Heights',
  weights: 'Weights',
  numberRange: 'Number Range',
  reset: 'Reset',
  apply: 'Apply',
  sort: 'Sort',
  sortPokemons: 'Sort Pokémons alphabetically or by National Pokédex number!',
  smallestNumber: 'Smallest number first',
  highest: 'Highest number first',
  aToZ: 'A-Z',
  zToA: 'Z-A',
  generations: 'Generations',
  useSearch: 'Use search for generations to explore your Pokémon!',
  generation1: 'Generation I',
  generation2: 'Generation II',
  generation3: 'Generation III',
  generation4: 'Generation IV',
  generation5: 'Generation V',
  generation6: 'Generation VI',
  generation7: 'Generation VII',
  generation8: 'Generation VIII',
  about: 'About',
  stats: 'Stats',
  evolution: 'Evolution',
  pokedextData: 'Pokédex Data',
  species: 'Species',
  height: 'Height',
  weight: 'Weight',
  abilities: 'Abilities',
  hidenAbilities: '(hidden ability)',
  training: 'Training',
  evYield: 'EV Yield',
  catchRate: 'Catch Rate',
  baseFriendship: 'Base Friendship',
  baseHappiness: 'Base Happiness',
  baseExp: 'Base Experience',
  growthRate: 'Growth Rate',
  breeding: 'Breeding',
  gender: 'Gender',
  eegGroups: 'Egg Groups',
  eegCycles: 'Egg Cycles',
  baseStats: 'Base Stats',
  hp: 'HP',
  attack: 'Attack',
  defense: 'Defense',
  spAtk: 'Sp. Atk',
  spDef: 'Sp. Def',
  speed: 'Speed',
  total: 'Total',
  theRanges:
    'The ranges shown on the right are for a level 100 Pokémon. Maximum values are based on a beneficial nature, 252 EVs, 31 IVs; minimum values are based on a hindering nature, 0 EVs, 0 IVs.',
  typeDefenses: 'Type Defenses',
  theEffectiveness: 'The effectiveness of each type on ',
  male: '♀ ',
  female: '♂ ',
  evolutionChart: 'Evolution Chart',
  level: 'Level ',
};
